language: java
sudo: required
jdk:
  - oraclejdk8
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install thrift-compiler
    - sudo ln -s /usr/bin/thrift /usr/local/bin/thrift
install:
    - which thrift
    - travis_retry mvn clean install
